apiVersion: 0.3.0
environments:
  ml-dev:
    destination:
      namespace: ml-dev
      server: http://192.168.64.2:8080
    k8sVersion: v1.13.2
    path: ml-dev
kind: ksonnet.io/app
libraries:
  kubeflow/chainer-job:
    name: chainer-job
    registry: kubeflow
    version: 1f19a61e701e816d470e5f9224d1cf9e2f797ef4
  kubeflow/common:
    name: common
    registry: kubeflow
    version: 1f19a61e701e816d470e5f9224d1cf9e2f797ef4
  kubeflow/examples:
    name: examples
    registry: kubeflow
    version: 1f19a61e701e816d470e5f9224d1cf9e2f797ef4
  kubeflow/tf-training:
    name: tf-training
    registry: kubeflow
    version: 1f19a61e701e816d470e5f9224d1cf9e2f797ef4
name: ml-example
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
